require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
prepare_react_native_project!

# Still using static linkage for React Native components
use_frameworks! :linkage => :static

target 'SpendX' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'HandleTxn' do
  # Extension now only needs to inherit paths for React/Native communication
  inherit! :search_paths 
end

post_install do |installer|
  react_native_post_install(
    installer,
    "../node_modules/react-native",
    :mac_catalyst_enabled => false
  )
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      
      # Since ML Kit is gone, we can clear out the architecture exclusions
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
      
      # Standard React Native & Extension fixes
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end